name: smart_farming
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.0.0
  google_fonts: ^6.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  firebase_core: ^3.0.0
  firebase_database: ^11.0.1
  timezone: ^0.9.2
  intl: ^0.19.0
  firebase_messaging: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pest_model/
